### ISSUE TITLE
Избыть NAN в integral.cpp

### ISSUE THREAD

**Issue by xredor** [MrKozelberg/GEC#1]

**Comment by MrKozelberg** [comment]
Обнаружена экспоненциальная расходимость параметризаций проводимостей (порядка E-14 S m^-1).. В поисках ошибки было установлено различие в параметризации стандартной атмосферы. Имеет место не соответствие параметризации давления в некоторых отдельных точках порядка E-11 [Pa].

Сравнивая ответы для давления на высоте 1.9 км (где достигается наибольшее отклонение) с ответом с сайта (https://www.digitaldutch.com/atmoscalc/index.htm), было обнаружено, что Ваша параметризация вернее соотносится с данными сайта (различие как раз в одиннадцатом знаке после запятой).

Планирую сравнить свою параметризацию с вариантом Фёдора, чтобы понять, что я делаю не так с параметризацией давления.

**Comment by MrKozelberg** [comment]
https://github.com/MrKozelberg/GEC/blob/d9231cc5138ada692ea73deab9aa3e886a233cea/integral.cpp#L31
Избыто

**Comment by MrKozelberg** [comment]
Наверное, тоже пора закрыть этот вопрос в связи с его решением.
