### ISSUE TITLE
Ошибка в параметризации проводимости

### ISSUE THREAD

**Issue by xredor** [MrKozelberg/GEC#2]

**Comment by MrKozelberg** [comment]
Ошибка в параметризации проводимости уменьшена до 15-16 значащего знака. Возможно дело в том, что сравниваю результаты работы двух разных языков программирования (С++ и Python), но лучше покажу Вам это при встрече.

**Comment by MrKozelberg** [comment]
Да, так и оказалось. Таким образом проблема решена.
