### ISSUE TITLE
Класс модели с широтно-долготной сеткой

### ISSUE THREAD

**Issue by xredor** [MrKozelberg/GEC#3]
Предлагается задачать шаг сетки по широте и долготе, из него считать количество ячеек по широте и долготе

**Comment by MrKozelberg** [comment]
Количество ячеек  считается (https://github.com/MrKozelberg/GEC/blob/47133a0b27dfb3f5a2e961ceeb551213c969069d/main.cpp#L202). 

Так же сама сетка параметризуется таким образом, что вычесленный по данной модели ионосферный потенциал сходится с аналитической оценкой.
